android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.resvalues=true
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.newDsl=false
org.gradle.jvmargs=-Xmx4096m
